DELETE http://localhost:5000/crud/DELETE/2
Content-Type: application/json

{
    "name":"hungasdasd",
    "username":"hungnh",
    "password":123,
    "email": "hungnh08@gmail.com",
    "phone": "0123123",
    "zipcode":"123",
    "city":"australia",
    "role":1
}
